name: super_stop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.0.0
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.4.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.0
  intl: ^0.20.2
  fl_chart: ^0.68.0
  confetti: ^0.7.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/fonts/
    - assets/icon/icon.png
    - assets/images/magic_hat.jpg
    - assets/images/super_shoes.jpg
  fonts:
    - family: Alef
      fonts:
        - asset: assets/fonts/Alef-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: "assets/icon/icon.png"
  android: true
  ios: true